"""Constants describing LF3R analysis artifacts and detail schemas."""

ANALYSIS_TABLE_FILES = {
    "method_coverage": "method_coverage.csv",
    "summary_by_method_signal_outcome": "summary_by_method_signal_outcome.csv",
    "summary_by_method_outcome": "summary_by_method_outcome.csv",
    "onset_signal_statistics": "onset_signal_statistics.csv",
    "clean_background_summary": "clean_background_summary.csv",
}
ANALYSIS_LOCALIZATION_TABLE_FILES = {
    "summary": "localization_summary.csv",
    "thresholds": "localization_thresholds.csv",
    "by_failure_type": "localization_by_failure_type.csv",
}
CHANGEPOINT_TABLE_FILES = {
    "summary": "changepoint_summary.csv",
    "reference_summary": "changepoint_reference_summary.csv",
    "by_failure_type": "changepoint_by_failure_type.csv",
    "scales": "changepoint_scales.csv",
    "method_coverage": "method_coverage.csv",
}
EVENT_TRIGGERED_TABLE_FILES = {
    "curves": "event_triggered_curves.csv",
    "change_scores": "event_triggered_change_scores.csv",
    "separation": "event_triggered_separation.csv",
    "summary": "event_triggered_summary.csv",
    "peak_events": "event_triggered_peak_events.csv",
    "controls": "event_triggered_controls.csv",
    "method_coverage": "method_coverage.csv",
}
ROBO_HOP_TABLE_FILES = {
    "sweep_summary": "sweep_summary.csv",
    "best_configs": "best_configs.csv",
    "recovery_results": "recovery_results.csv",
    "breakdown_summary": "breakdown_summary.csv",
    "ensemble_sweep": "ensemble_sweep.csv",
    "ensemble_selected": "ensemble_selected.csv",
    "ensemble_by_failure_type": "ensemble_by_failure_type.csv",
    "interval_localization": "interval_localization_ranking.csv",
    "offline_localization_diagnostics": "offline_localization_diagnostics.csv",
}
ROBO_HOP_REQUIRED_FILES = (
    "metadata.json",
    "sweep_summary.csv",
    "event_results.csv",
    "clean_rollout_results.csv",
    "best_configs.csv",
    "recovery_results.csv",
    "breakdown_summary.csv",
)
ROBO_LOCALIZATION_HEAD_REQUIRED_FILES = (
    "metadata.json",
    "ablation_comparison.csv",
    "ablation_delta.csv",
    "per_split_metrics.csv",
    "per_rollout_predictions.csv",
    "training_records.json",
    "split_manifest.json",
    "conclusion.md",
)
ROBO_LABEL_LOSS_REQUIRED_FILES = (
    "metadata.json",
    "label_ablation.csv",
    "loss_ablation.csv",
    "per_split_metrics.csv",
    "per_rollout_predictions.csv",
    "dataset_targets.csv",
    "dataset_target_summary.json",
    "training_records.json",
    "split_manifest.json",
    "best_configuration.json",
    "best_configuration.md",
)

ROBO_HOP_EXTENDED_FILES = (
    "no_event_failure_results.csv",
    "ensemble_sweep.csv",
    "ensemble_selected.csv",
    "ensemble_by_failure_type.csv",
    "interval_localization_ranking.csv",
    "offline_localization_diagnostics.csv",
    "grasp_event_features.csv",
    "grasp_detected_vs_missed.csv",
    "grasp_matched_control.csv",
    "grasp_matched_control_summary.csv",
    "grasp_failure_categories.csv",
    "grasp_failure_category_summary.csv",
)

# These allowlists are deliberately kept server-side. The Analysis page can
# browse high-cardinality CSV/JSONL artifacts without turning the generic file
# server into an arbitrary-file reader.
ANALYSIS_DETAIL_KINDS = {
    "changepoint_summary": ("change_point", "changepoint_summary.csv"),
    "changepoint_failure_types": ("change_point", "changepoint_by_failure_type.csv"),
    "changepoint_events": ("change_point", "changepoint_event_metrics.jsonl"),
    "changepoint_comparison": ("change_point", "comparison_with_full_136_20260827.csv"),
    "localization_summary": ("change_point", "localization_summary.csv"),
    "localization_thresholds": ("change_point", "localization_thresholds.csv"),
    "localization_failure_types": ("change_point", "localization_by_failure_type.csv"),
    "localization_events": ("change_point", "localization_event_metrics.jsonl"),
    "event_triggered_summary": ("event_triggered", "event_triggered_summary.csv"),
    "event_triggered_peaks": ("event_triggered", "event_triggered_peak_events.csv"),
    "event_triggered_curves": ("event_triggered", "event_triggered_curves.csv"),
    "event_triggered_change_scores": ("event_triggered", "event_triggered_change_scores.csv"),
    "legacy_anomalies": ("legacy", "event_metrics.jsonl"),
}
ANALYSIS_DETAIL_FILTERS = {
    "method", "signal", "feature", "scale", "threshold", "outcome",
    "failure_type", "task",
}
ANALYSIS_DETAIL_SORTS = {
    "score", "event_score", "localization_error", "peak_distance", "recall",
    "false_alarm", "f1", "auroc", "rollout", "task",
}
ANALYSIS_ARTIFACT_NAMES = {
    "REPORT.md",
    "metadata.json",
    "method_coverage.csv",
    "summary_by_method_signal_outcome.csv",
    "summary_by_method_outcome.csv",
    "onset_signal_statistics.csv",
    "clean_background_summary.csv",
    "event_metrics.jsonl",
    "localization_summary.csv",
    "localization_thresholds.csv",
    "localization_by_failure_type.csv",
    "localization_event_metrics.jsonl",
    "changepoint_summary.csv",
    "changepoint_reference_summary.csv",
    "changepoint_by_failure_type.csv",
    "changepoint_scales.csv",
    "changepoint_event_metrics.jsonl",
    "comparison_with_full_136_20260827.csv",
    "event_triggered_curves.csv",
    "event_triggered_change_scores.csv",
    "event_triggered_separation.csv",
    "event_triggered_summary.csv",
    "event_triggered_peak_events.csv",
    "event_triggered_controls.csv",
    "sweep_summary.csv",
    "event_results.csv",
    "no_event_failure_results.csv",
    "clean_rollout_results.csv",
    "best_configs.csv",
    "recovery_results.csv",
    "breakdown_summary.csv",
    "ensemble_sweep.csv",
    "ensemble_selected.csv",
    "ensemble_by_failure_type.csv",
    "interval_localization_ranking.csv",
    "grasp_event_features.csv",
    "grasp_detected_vs_missed.csv",
    "grasp_matched_control.csv",
    "grasp_matched_control_summary.csv",
    "grasp_failure_categories.csv",
    "grasp_failure_category_summary.csv",
    "grasp_event_heatmap.png",
    "task_cv_results.csv",
}
CHANGEPOINT_EVENT_FIELDS = (
    "method",
    "signal",
    "scale_frames",
    "feature",
    "feature_label",
    "threshold",
    "threshold_value",
    "rollout_id",
    "event_index",
    "event_type",
    "outcome_group",
    "failure_type",
    "event_frame",
    "observable_onset_frame",
    "recovery_frame",
    "terminal_failure_frame",
    "next_event_frame",
    "event_window_low",
    "event_window_high_exclusive",
    "onset_candidate_frame",
    "onset_candidate_distance_frames",
    "onset_feature_value",
    "onset_score",
    "peak_frame",
    "peak_feature_value",
    "peak_score",
    "peak_signed_offset_frames",
    "peak_distance_frames",
    "first_exceedance_frame",
    "first_exceedance_signed_offset_frames",
    "first_exceedance_absolute_error_frames",
    "feature_valid",
    "hit",
    "miss",
    "early_peak",
    "early_first_exceedance",
    "onset_near_unusual",
    "direction_after_unusual",
    "failure_direction_consistent",
    "native_samples_only",
    "clean_success_false_alarm_rate",
    "same_rollout_non_onset_false_alarm_rate",
    "clean_pseudo_events",
    "false_alarm_count",
    "false_alarm_rate",
    "true_positives",
    "false_positives",
    "false_negatives",
    "precision",
    "f1",
    "auroc",
    "average_precision",
    "task_suite",
    "task_id",
    "task_description",
    "source_kind",
    "analysis_partition",
    "dataset_role",
)
ANALYSIS_LOCALIZATION_EVENT_FIELDS = (
    "method",
    "signal",
    "threshold",
    "threshold_value",
    "rollout_id",
    "event_index",
    "event_type",
    "outcome_group",
    "failure_type",
    "event_frame",
    "observable_onset_frame",
    "recovery_frame",
    "terminal_failure_frame",
    "next_event_frame",
    "window_low",
    "window_high_exclusive",
    "pre_center",
    "robust_scale",
    "event_score",
    "score_peak_frame",
    "score_peak_offset_frames",
    "first_alarm_frame",
    "first_post_onset_frame",
    "signed_lead_lag_frames",
    "post_onset_delay_frames",
    "localization_error_frames",
    "absolute_localization_error_frames",
    "hit",
    "miss",
    "early_alarm",
    "native_samples_only",
    "clean_pseudo_event_count",
    "hit_within_4_frames",
    "hit_within_8_frames",
    "hit_within_16_frames",
    "hit_within_30_frames",
    "task_suite",
    "task_id",
    "task_description",
    "source_kind",
    "analysis_partition",
    "dataset_role",
)
ANALYSIS_EVENT_FIELDS = (
    "rollout_id",
    "event_index",
    "event_type",
    "outcome_group",
    "failure_type",
    "is_background",
    "event_frame",
    "recovery_frame",
    "terminal_failure_frame",
    "next_event_frame",
    "recovery_offset_frames",
    "method",
    "signal",
    "normalized_response_magnitude",
    "normalized_failure_oriented_response",
    "post_event_persistence_fraction",
    "post_event_persistence_median_oriented",
    "recovery_rebound_normalized",
    "recovery_fraction_toward_baseline",
    "clean_background_response_q95",
    "clean_background_response_percentile",
    "native_direction",
    "pre_window_requested_frames",
    "post_window_requested_frames",
    "pre_sample_count",
    "post_sample_count",
    "persistence_sample_count",
    "post_window_fallback",
    "pre_center",
    "pre_mad",
    "raw_pre_scale",
    "robust_pre_scale",
    "robust_scale_source",
    "post_center",
    "recovery_sample_frame",
    "recovery_frame_nearest_sample_error",
    "recovery_value",
    "recovery_rebound_signed_change",
    "recovery_rebound_toward_baseline",
    "clean_background_pseudo_event_count",
    "clean_background_response_median",
)
ANALYSIS_EVENT_ARRAY_FIELDS = {
    "pre_sample_frames",
    "post_sample_frames",
    "persistence_sample_frames",
}
ANALYSIS_RECORD_FIELDS = (
    "task_suite",
    "task_id",
    "task_description",
    "source_kind",
    "analysis_partition",
    "dataset_role",
)
