"""Baseline method and option contracts shared by backend services."""

BASELINE_METHODS = (
    "safe",
    "procvlm",
    "rynnvalue",
    "robo_dopamine",
    "densereward",
)
BASELINE_LABELS = {
    "safe": "SAFE",
    "procvlm": "ProcVLM",
    "rynnvalue": "RynnValue",
    "robo_dopamine": "Robo-Dopamine",
    "densereward": "DenseReward",
}
BASELINE_RUN_STATUSES = {
    "complete",
    "complete_with_errors",
}
BASELINE_RESULT_FILTERS = {
    "all",
    "missing_valid",
}
INSTRUCTION_VARIANT_LABELS = {
    "full_instruction": "Full instruction",
    "subtask_a": "A",
    "subtask_b": "B",
}
BASELINE_METHOD_OPTION_FIELDS = {
    "safe": {
        "render_video",
        "validate_environment",
        "dry_run",
    },
    "procvlm": {
        "model_path",
        "dtype",
        "tensor_parallel_size",
        "procvlm_window_size",
        "procvlm_frame_stride",
        "procvlm_max_sampled_frames",
        "procvlm_max_new_tokens",
        "procvlm_enable_value_head",
        "procvlm_procedure_mode",
        "procvlm_procedure_config",
        "procvlm_tracker_support_threshold",
        "procvlm_tracker_window_size",
        "procvlm_tracker_max_forward_jump",
        "render_video",
        "validate_environment",
        "dry_run",
    },
    "rynnvalue": {
        "model_path",
        "rynn_num_frames",
        "rynn_num_steps",
        "rynn_evaluation_interval",
        "rynn_batch_size",
        "rynn_max_image_side",
        "rynn_max_new_tokens",
        "robot_description",
        "camera_description",
        "render_video",
        "validate_environment",
        "dry_run",
    },
    "robo_dopamine": {
        "model_path",
        "dtype",
        "tensor_parallel_size",
        "robo_frame_interval",
        "robo_batch_size",
        "robo_eval_mode",
        "robo_camera_mode",
        "goal_image",
        "robo_localization_ckpt",
        "render_video",
        "validate_environment",
        "dry_run",
    },
    "densereward": {
        "model_path",
        "densereward_frame_interval",
        "densereward_max_new_tokens",
        "validate_environment",
        "dry_run",
    },
}
BASELINE_ADVANCED_FIELDS = {
    "model_path",
    "dtype",
    "tensor_parallel_size",
    "procvlm_window_size",
    "procvlm_frame_stride",
    "procvlm_max_sampled_frames",
    "procvlm_max_new_tokens",
    "procvlm_enable_value_head",
    "procvlm_procedure_mode",
    "procvlm_procedure_config",
    "procvlm_tracker_support_threshold",
    "procvlm_tracker_window_size",
    "procvlm_tracker_max_forward_jump",
    "rynn_num_frames",
    "rynn_num_steps",
    "rynn_evaluation_interval",
    "rynn_batch_size",
    "rynn_max_image_side",
    "rynn_max_new_tokens",
    "robot_description",
    "camera_description",
    "robo_frame_interval",
    "robo_batch_size",
    "robo_eval_mode",
    "robo_camera_mode",
    "goal_image",
    "robo_localization_ckpt",
    "densereward_frame_interval",
    "densereward_max_new_tokens",
    "render_video",
    "validate_environment",
    "dry_run",
}
